title: Yimeng Wang
url: https://YimengYvonne.github.io

# Owner/author information
owner:
  name: Yimeng Wang
  avatar: wym.jpg
  email: ywang139@wm.edu
  linkedin: yimeng-wang-849aa9276
  scholar: https://scholar.google.com/citations?user=sx33W_4AAAAJ
  cv: https://YimengYvonne.github.io/resume.pdf
  

# Analytics and webmaster tools stuff goes here
# https://search.google.com/search-console/ownership
google_verify: "29Kc7Giiy4jwktyeWMNRSP5PYCsujTKU3ph4Kviyoss"

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify: ""

# Links to include in top navigation
# For external links add external: true
links:
  - title: About Me
    url: /
  - title: Publications
    url: /publications/
  - title: Experiences
    url: /Experiences/
  - title: Service
    url: /Service/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: USA/EST
future: true
highlighter: rouge
# markdown: kramdown
# markdown: redcarpet
# pygments: true


# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   "/:categories/:title"


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  # coderay:
  #   coderay_line_numbers:
  #   coderay_line_numbers_start: 1
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: class


# disqus settings:
disqus:
  shortname: lancecai

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]

